# Generated by Django 3.2.16 on 2023-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro_his_paciente',
            name='Id_Paciente',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
