# Generated by Django 3.2.16 on 2023-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0002_alter_maestro_his_paciente_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro_his_nuevo_archivo_plano',
            name='Id_Cita',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maestro_his_paciente',
            name='Id_Paciente',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
