# Generated by Django 3.2.16 on 2023-05-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0003_auto_20230503_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro_his_registrador',
            name='Fecha_Nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
