# Generated by Django 3.2.16 on 2023-07-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0003_alter_data_cnv_cnv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Teléfono',
            new_name='Telefono',
        ),
    ]
