# Generated by Django 3.2.16 on 2023-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0004_alter_maestro_his_registrador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro_his_centro_poblado',
            name='Altitud_Centro_Poblado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestro_his_centro_poblado',
            name='Id_Codigo_Centro_Poblado',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestro_his_centro_poblado',
            name='Id_Ubigueo_Centro_Poblado',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
