# Generated by Django 3.2.16 on 2023-07-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0004_rename_teléfono_data_cnv_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Profesión',
            new_name='Malfcongenita',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Perímetrocefálico',
            new_name='Perimetrocefalico',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Perímetrotorácico',
            new_name='Perimetrotoracico',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Malfcongénita',
            new_name='Profesion',
        ),
    ]
