# Generated by Django 3.2.16 on 2023-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0005_auto_20230516_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_CNV',
            fields=[
                ('CNV', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('CodEESS', models.CharField(blank=True, max_length=255, null=True)),
                ('EESS', models.CharField(blank=True, max_length=255, null=True)),
                ('pApellidoMadre', models.CharField(blank=True, max_length=255, null=True)),
                ('sApellidoMadre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombresMadre', models.CharField(blank=True, max_length=255, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('FecNac', models.CharField(blank=True, max_length=255, null=True)),
                ('Gest_Sem', models.IntegerField(blank=True, null=True)),
                ('TipoDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('Documento', models.CharField(blank=True, max_length=255, null=True)),
                ('Teléfono', models.CharField(blank=True, max_length=255, null=True)),
                ('CodEESSPrenatal', models.CharField(blank=True, max_length=255, null=True)),
                ('EESSPrenatal', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('Hora', models.TimeField(blank=True, null=True)),
                ('Sexo', models.CharField(blank=True, max_length=255, null=True)),
                ('Peso_g', models.IntegerField(blank=True, null=True)),
                ('Talla_cm', models.IntegerField(blank=True, null=True)),
                ('Apgar', models.IntegerField(blank=True, null=True)),
                ('Perímetrocefálico', models.IntegerField(blank=True, null=True)),
                ('Perímetrotorácico', models.IntegerField(blank=True, null=True)),
                ('Malfcongénita', models.CharField(blank=True, max_length=255, null=True)),
                ('TiempoLigCord', models.CharField(blank=True, max_length=255, null=True)),
                ('Lactanciaprecoz', models.CharField(blank=True, max_length=255, null=True)),
                ('pApellidoProfesional', models.CharField(blank=True, max_length=255, null=True)),
                ('sApellidoProfesional', models.CharField(blank=True, max_length=255, null=True)),
                ('nombresProfesional', models.CharField(blank=True, max_length=255, null=True)),
                ('Profesión', models.CharField(blank=True, max_length=255, null=True)),
                ('NColegio', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaRegistro', models.CharField(blank=True, max_length=255, null=True)),
                ('pApellidoResgistrador', models.CharField(blank=True, max_length=255, null=True)),
                ('sApellidoRegistrador', models.CharField(blank=True, max_length=255, null=True)),
                ('nombresRegistrador', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPartoId', models.IntegerField(blank=True, null=True)),
                ('tipoParto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'DATA_CNV',
                'db_table': 'DATA_CNV',
            },
        ),
    ]
